version: '3'

services:
    teahouse-api:
        build: ./teahouse
        volumes:
            - ./teahouse/src:/usr/src/app
            - ./storage/logs:/usr/src/app/storage/logs
            - ./storage/chatrooms:/usr/src/app/storage/chatrooms
        ports:
            - 13337:13337

    healthcheck:
        build: ./healthcheck
        volumes:
            - ./healthcheck:/usr/src/app
            - ./teahouse/src:/usr/src/teahouse
            - ./storage/logs:/usr/src/app/storage/logs
            - ./storage/chatrooms:/usr/src/app/storage/chatrooms

